[package]
name = "minigrep"
version = "0.1.0"
edition = "2021"
authors = ["Gresham Dave C <greyashdave@gmail.com>"]
description = "A simple grep-like CLI tool"
license = "MIT"
repository = "https://github.com/Greyash-Dave/minigrep.git"

[dependencies]

[[bin]]
name = "minigrep"
path = "src/main.rs"